### ISSUE TITLE
Incompatible with Swift 3

### ISSUE THREAD

**Issue by cbanowsky** [PiXeL16/SwiftMailgun#1]
Currently Mailgun does not work with new release of Swift 3.  I had to delete it from my project to get my app to compile.  An update would be great.

**Comment by PiXeL16** [comment]
Yep, sorry about that, but my time is very limited these days. `PRs` are very welcome 👍

**Comment by PiXeL16** [comment]
Hey, Just release `1.0.0` with Swift 3.0 support https://cocoapods.org/pods/SwiftMailgun
Thanks everyone for the help!
