### ISSUE TITLE
Swift 4 Support

### ISSUE THREAD

**Issue by DIMEGLIOM** [PiXeL16/SwiftMailgun#7]
I have an app currently in development and I am using your work here to help with sending emails to my users. Will the code here still work when I update to swift 4? Thanks for your time I really appreciate it.

**Comment by DIMEGLIOM** [comment]
The following code for the StringExtensions.h file should be corrected to the following to work with Swift 4/new Xcode 
`import Foundation

// MARK: - Extension to remove HTML Attributes from Strings
public extension String {
    
    var htmlToAttributedString: NSAttributedString? {
        guard
            let data = data(using: String.Encoding.utf8)
            else { return nil }
        do {
           // return try NSAttributedString(data: data, options: [NSDocumentTypeDocumentAttribute:NSHTMLTextDocumentType,NSCharacterEncodingDocumentAttribute:NSNumber(value: String.Encoding.utf8.rawValue)], documentAttributes: nil)
            return try NSAttributedString(data: data, options: [.documentType: NSAttributedString.DocumentType.html,
                                                                .characterEncoding: String.Encoding.utf8.rawValue], documentAttributes: nil)
        } catch let error as NSError {
            print(error.localizedDescription)
            return  nil
        }
    }
    
    var htmlToString: String {
        return htmlToAttributedString?.string ?? ""
    }
}`

**Comment by kutakmir** [comment]
@PiXeL16 can you please merge the pull request? :)
